### ISSUE TITLE
can't load package: package github.com/rongcloud/server-sdk-go

### ISSUE THREAD

**Issue by mysterytree** [rongcloud/server-sdk-go#14]
用的是gvm安装的go1.6.2
执行go get github.com/astaxie/beego/httplib正常
但是 go get github.com/rongcloud/server-sdk-go时候报错

```
can't load package: package github.com/rongcloud/server-sdk-go: no buildable Go source files in /Users/hu/.gvm/pkgsets/go1.6.2/global/src/github.com/rongcloud/server-sdk-go
```

**Comment by mysterytree** [comment]
![image](https://cloud.githubusercontent.com/assets/6166794/18458992/a1afeede-7998-11e6-8bf9-c06cc89d57c8.png)

**Comment by Jarvan89** [comment]
https://github.com/rongcloud/server-sdk-go/RCServerSDK

**Comment by Jarvan89** [comment]
go get github.com/rongcloud/server-sdk-go/RCServerSDK

**Comment by m198799** [comment]
新版请使用，go get github.com/rongcloud/server-sdk-go/sdk。
