### ISSUE TITLE
structs.go 文件 result 拼写

### ISSUE THREAD

**Issue by JaxSONG** [rongcloud/server-sdk-go#17]
> /**
 *getToken 返回结果
 */
type TokenReslut struct {
	Code int `json:"code"`
	Token string `json:"token"`
	UserId string `json:"userId"`
	ErrorMessage string `json:"errorMessage"`
}

`TokenReslut` 应该改为 `TokenResult`

**Comment by JaxSONG** [comment]
包括下面几个带有 `Reslut` 的命名

**Comment by m198799** [comment]
v3版本已经修复，感谢您的建议。
