### ISSUE TITLE
发送单聊消息怎么带用户信息

### ISSUE THREAD

**Issue by JaxSONG** [rongcloud/server-sdk-go#19]
`/**
文本消息。
*/
type TxtMessage struct {
	Content     string `json:"content"`
	Extra       string `json:"extra"`
	messageType string
}`
这里怎么携带用户信息？

**Comment by m198799** [comment]
消息体里无法携带用户信息。

**Comment by 0x1306a94** [comment]
@JaxSONG  将你的`用户信息序列化为字符串格式`然后 放到 `Extra`  字段里面, 客户端接受到消息后在`根据Extra 字段字符串反序列化`

**Comment by m198799** [comment]
#40
