### ISSUE TITLE
群组消息

### ISSUE THREAD

**Issue by JaxSONG** [rongcloud/server-sdk-go#20]
群组消息官方文档 不同内置消息类型，有不同的字段，像小灰条消息
`{"message":"请在聊天中注意人身财产安全","extra":""}`
那怎么可以发送？

> /**
文本消息。
*/
type TxtMessage struct {
	Content     string `json:"content"`
	Extra       string `json:"extra"`
	messageType string
}

**Comment by m198799** [comment]
rc := NewRongCloud(
		"输入用户app key",
		"输入用户app secret",
		nil,
	)

	msg := MsgContent{
		Content: "请在聊天中注意人身财产安全",
		Extra:   "",
	}

	err := rc.GroupSend(
		"发送消息的用户ID",
		"接受不了消息的组ID",
		"RC:TxtMsg",
		msg,
		"",
		"",
		1,
		0,
		1,
	)
