### ISSUE TITLE
官网上提供的接口参数和代码实现不一致

### ISSUE THREAD

**Issue by ninefivefly** [rongcloud/server-sdk-go#39]
官网提供的：发送系统消息、发送单聊消息接口，有“contentAvailable”字段

代码里面多了个“isCounted”, 少了”contentAvailable“字段
>req.Param("content", msgr)
>req.Param("pushData", pushData)
>req.Param("pushContent", pushContent)
>req.Param("count", strconv.Itoa(count))
>req.Param("isPersisted", strconv.Itoa(isPersisted))
>req.Param("isCounted", strconv.Itoa(isCounted))

**Comment by m198799** [comment]
您好：
       isCounted 为老版本所提供的参数，contentAvailable 是近期新增加的。我们会在稍后进行同步，感谢你的支持。

**Comment by m198799** [comment]
fix: 修复PrivateSend参数, 删除isCounted, 增加contentAvailable.#41
