### ISSUE TITLE
PrivateSend请求超时代码有问题

### ISSUE THREAD

**Issue by snowcrumble** [rongcloud/server-sdk-go#45]
https://github.com/rongcloud/server-sdk-go/blob/master/sdk/message.go#L439
`req.SetTimeout(time.Second*rc.timeout, time.Second*rc.timeout)`
两个time.Duration相乘是天文数字了

**Comment by JinesD** [comment]
req.SetTimeout 这个方法，需要两个参数，默认都是 3 秒
