### ISSUE TITLE
go mod 模式下默认加载的是 v2.0.1 版本.

### ISSUE THREAD

**Issue by oldfeel** [rongcloud/server-sdk-go#48]
go mod 模式下使用
````
go get github.com/rongcloud/server-sdk-go
````
加载的是 v2.0.1,需要手动修改为
````
go get github.com/rongcloud/server-sdk-go@master
````
才能加载最新版本.

**Comment by huhaifan** [comment]
+1

**Comment by insistent** [comment]
+1

**Comment by panda8z** [comment]
+1 

`require github.com/rongcloud/server-sdk-go v2.0.1+incompatible // indirect
`

**Comment by htlhenry** [comment]
建议升级到v3版本，请参考[README](https://github.com/rongcloud/server-sdk-go?tab=readme-ov-file#2-go-mode-%E6%96%B9%E5%BC%8F%E4%BD%BF%E7%94%A8-v3)
