### ISSUE TITLE
go mod tidy failed

### ISSUE THREAD

**Issue by Halimao** [rongcloud/server-sdk-go#53]
get https://github.com/belogik/goes return 404

**Comment by Halimao** [comment]
![image](https://user-images.githubusercontent.com/25278203/87293442-e342d280-c534-11ea-9f8e-855e1e36819f.png)

**Comment by Halimao** [comment]
![image](https://user-images.githubusercontent.com/25278203/87293504-fbb2ed00-c534-11ea-9e0e-3b664e388150.png)

**Comment by Halimao** [comment]
可以更新下beego的版本吗
https://github.com/astaxie/beego/issues/3251

**Comment by SpringDRen** [comment]
已修复
