### ISSUE TITLE
发送系统消息 MessageSystemPublish 如果有多个用户的话,只有最后一个 id 能收到消息

### ISSUE THREAD

**Issue by oldfeel** [rongcloud/server-sdk-go#7]
我觉得问题是在使用 httplib 这个框架时出现的.

    for _, toUserId := range toUserIds {
		req.Param("toUserId", toUserId)
    }

这里的 param 是个 map[string]string,所以同一 key 无法被重复保存吧.

**Comment by yesidi** [comment]
好，我現在看看。等下回復你

**Comment by yesidi** [comment]
有这个问题，这几天会更新个版本修复这个问题。

**Comment by oldfeel** [comment]
辛苦了.大牛!

**Comment by oldfeel** [comment]
暂时可以用这个代替

	func MessageSystemPublish(fromUserId string, toUserIds []string, objectName, content, pushContent, pushData string) {
		destinationUrl := "https://api.cn.rong.io/message/system/publish.json"
	
		u := url.Values{}
		u.Add("fromUserId", fromUserId)
		for _, toUserId := range toUserIds {
			u.Add("toUserId", toUserId)
		}
		u.Add("objectName", objectName)
		u.Add("content", content)
		u.Add("pushContent", pushContent)
		u.Add("pushData", pushData)
	
		req, err := http.NewRequest("POST", destinationUrl, bytes.NewBufferString(u.Encode()))
		if err != nil {
			fmt.Println(err.Error())
		}
	
		nonce, timestamp, signature := getSignature()
		req.Header.Set("App-Key", RONGCLOUD_APP_KEY)
		req.Header.Set("Nonce", nonce)
		req.Header.Set("Timestamp", timestamp)
		req.Header.Set("Signature", signature)
		req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	
		client := &http.Client{}
		res, _ := client.Do(req)
		defer res.Body.Close()
		body, err := ioutil.ReadAll(res.Body)
		if err != nil {
			fmt.Println(err.Error())
		}
		fmt.Println("body is " + string(body))
	}
	
	//本地生成签名
	//Signature (数据签名)计算方法：将系统分配的 App Secret、Nonce (随机数)、
	//Timestamp (时间戳)三个字符串按先后顺序拼接成一个字符串并进行 SHA1 哈希计算。如果调用的数据签名验证失败，接口调用会返回 HTTP 状态码 401。
	func getSignature() (nonce, timestamp, signature string) {
		nonceInt := rand.Int()
		nonce = strconv.Itoa(nonceInt)
		timeInt64 := time.Now().Unix()
		timestamp = strconv.FormatInt(timeInt64, 10)
		h := sha1.New()
		io.WriteString(h, RONGCLOUD_APP_SECRET+nonce+timestamp)
		signature = fmt.Sprintf("%x", h.Sum(nil))
		return
	}

**Comment by arielyang** [comment]
@oldfeel 可以 fork 项目然后提交 Pull request 给我们 :-)

**Comment by oldfeel** [comment]
Ok
